name: 'Setup Serverless'
description: '⚡:octocat: Setup a Serverless environment by matchers optionally downloading and adding it to the PATH.'
inputs:
  serverless_version:
    description: "Version Spec of the version to use.  Examples: 2.4.0, ~2.0.0, ^2.0.0"
    required: false
    default: latest
  provider:
    required: true
    description: 'Provider of the serverless.'
outputs:
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit.'
  serverless_version:
    description: 'The installed serverless version.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'zap'
  color: black
