name: 'Setup Serverless environment'
description: '⚡:octocat: A Github Action for deploying with the Serverless Framework'
inputs:
  severless-version:
    description: "Version Spec of the version to use.  Examples: 2.4.0, ~2.0.0, ^2.0.0"
    required: false
    default: latest
  provider:
    required: true
    description: 'Provider of the serverless.'
  secretId:
    required: true
    description: 'Secret ID of the provider to ues.'
  secretKey:
    required: true
    description: 'Secret Key of the provider to ues.'
  tencent_appid:
    required: false
    description: 'Appid of the tencent cloud to ues.'
  aliyun_account_id:
    required: false
    description: 'Account ID of the aliyun to ues.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'zap'
  color: black
