name: 'Setup Serverless environment'
description: '⚡:octocat: A Github Action for deploying with the Serverless Framework'
inputs:
  serverless_version:
    description: "Version Spec of the version to use.  Examples: 2.4.0, ~2.0.0, ^2.0.0"
    required: false
    default: latest
  provider:
    required: true
    description: 'Provider of the serverless.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'zap'
  color: black
