name: 'setup-serverless'
description: '⚡:octocat: A Github Action for deploying with the Serverless Framework'
inputs:
  severless-version:
    required: false
    default: latest
  provider:
    required: true
    description: 'input description here'
  secretId:
    required: true
    description: 'input description here'
  secretKey:
    required: true
    description: 'input description here'
  tencent_appid:
    required: false
  aliyun_account_id:
    required: false
runs:
  using: 'node14'
  main: 'dist/index.js'
branding:
  icon: 'zap'
  color: black
