name: Bug Report
description: Create a report to help us improve
body:
  - type: input
    attributes:
      label: Action Version
      description: 'e.g. v2.0.6'
    validations:
      required: true
  - type: input
    attributes:
      label: Severless Version
      description: 'e.g. v3.16.0'
    validations:
      required: true
  - type: input
    attributes:
      label: Node Version
      description: 'e.g. v18.9.0'
    validations:
      required: false
  - type: input
    attributes:
      label: NPM/Yarn Version
      description: 'e.g. NPM v8.19.0, Yarn v1.22.10'
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error messages
      render: markdown