name: 'Continuous Integration'
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '.github/workflows/continuous-integration.yml'
  pull_request:
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '.github/workflows/continuous-integration.yml'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        node: [ '16', '18', '19' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Prettier Format Check
        run: npm run format-check

      - name: ESLint Check
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: npm test

      - name: Send Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: github-actions-codecov-${{ matrix.os }}
          fail_ci_if_error: false
          verbose: true

