name: 'Continuous Integration'
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '.github/workflows/continuous-integration.yml'
  pull_request:
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '**.lock'
      - '.github/workflows/continuous-integration.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-dist:
    name: Check dist/ directory
    uses: actions/reusable-workflows/.github/workflows/check-dist.yml@a8533f184b279cfc1b2dd6a96ed2f097ccf81189

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        node: [ '16', '18', '19' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - name: Prettier Format Check
        run: npm run format-check

      - name: ESLint Check
        run: npm run lint

      - name: Cache dist
        uses: actions/cache@v3
        with:
          path: ./dist
          key: ${{ runner.os }}-dist-${{ hashFiles('./dist/index.js') }}

      - name: Verify
        run: yarn build

      - name: Test
        run: yarn test

      - name: Send Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          name: github-actions-codecov-${{ matrix.os }}
          fail_ci_if_error: false
          verbose: true

