name: 'Setup Serverless'

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash
    working-directory: ./

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  TENCENT_APPID: ${{ secrets.TENCENT_APPID }}
  TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
  TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY}}
  GCLOUD_KEYFILE: ${{ secrets.GCLOUD_KEYFILE }}
  CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
  CLOUDFLARE_AUTH_EMAIL: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}
  OW_AUTH: ${{ secrets.OW_AUTH }}
  OW_APIHOST: ${{ secrets.OW_APIHOST }}
  ALICLOUD_ACCOUNT_ID: ${{ secrets.ALICLOUD_ACCOUNT_ID }}
  ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
  ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY}}

jobs:
  serverless-versions:
    name: 'Setup Serverless'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        serverless-versions: [ 1.83.0, 2.42.0, latest ]
        providers: [ 'aws','azure','tencent','gcloud','cloudflare-workers','fn','kubeless','openwhisk','aliyun' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2.1.7
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - uses: actions/cache@v2.1.7
        with:
          path: ./dist
          key: ${{ runner.os }}-dist-${{ hashFiles('./dist/index.js') }}

      - run: yarn build

      - name: Setup Serverless - ${{ matrix['serverless-versions'] }}
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          serverless_version: ${{ matrix['serverless-versions'] }}
          provider: ${{ matrix['providers'] }}

      - name: Validate Teraform Version - ${{ matrix['serverless-versions'] }}
        if: ${{ matrix['serverless-versions'] != 'latest' }}
        run: sls -v

      - name: Validate Teraform Version - ${{ matrix['serverless-versions'] }}
        if: ${{ matrix['serverless-versions'] == 'latest' }}
        run: sls -v