name: 'Build Test'
on: # rebuild any PRs and main branch changes
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run format-check
      - run: npm run build
      - name: Commit changed files
        if: ${{ always() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dist/index.js
          branch: ${{ github.head_ref }}